title: Exocore

source: .
url: https://exocore.remilia.org
baseurl: ''
destination: _site
repository: remiliacorp/exocore


background: "red"

highlighter: rouge

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  enabled: true

sass:
    sass_dir: ./exocore/_sass

layouts_dir: ./exocore/_layouts
includes_dir: ./exocore/_includes
plugins_dir: ./exocore/_plugins
data_dir: ./data

permalink: pretty

      
defaults:
  - scope:
      path: "" 
    values:
      layout: "default"
      date: "Jan 1 2000"
  - scope:
      path: ""
      type: "articles"
    values: 
      layout: "article"
  - scope:
      path: ""
      type: "journal"
    values: 
      layout: "journal"
  - scope:
      path: ""
      type: "notes"
    values: 
      layout: "note"

collections:

  notes:
    output: true
    
  journal:
    output: true
    
  articles:
    output: true
    
relative_links:
  enabled:     true
  collections: true
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
    
graphviz:
  options: "-Tsvg" # 'dot' command option
  command: "dot"   # execute this string. specify full path to 'dot' if you need


plugins:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-github-metadata
- jekyll-seo-tag
- html-proofer
- rubocop
- w3c_validators
- jekyll-last-modified-at
- jekyll-redirect-from
#- jekyll-feed
- jekyll-wikilinks
- ruby-graphviz

